/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AppointmentUpdateManyWithoutAgentsInput } from "./AppointmentUpdateManyWithoutAgentsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { AssignmentUpdateManyWithoutAgentsInput } from "./AssignmentUpdateManyWithoutAgentsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { UserUpdateManyWithoutAgentsInput } from "./UserUpdateManyWithoutAgentsInput";

@InputType()
class AgentUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AppointmentUpdateManyWithoutAgentsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentUpdateManyWithoutAgentsInput)
  @IsOptional()
  @Field(() => AppointmentUpdateManyWithoutAgentsInput, {
    nullable: true,
  })
  appointments?: AppointmentUpdateManyWithoutAgentsInput;

  @ApiProperty({
    required: false,
    type: () => AssignmentUpdateManyWithoutAgentsInput,
  })
  @ValidateNested()
  @Type(() => AssignmentUpdateManyWithoutAgentsInput)
  @IsOptional()
  @Field(() => AssignmentUpdateManyWithoutAgentsInput, {
    nullable: true,
  })
  assignments?: AssignmentUpdateManyWithoutAgentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutAgentsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutAgentsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutAgentsInput, {
    nullable: true,
  })
  users?: UserUpdateManyWithoutAgentsInput;
}

export { AgentUpdateInput as AgentUpdateInput };
